import { StyleSheet } from 'react-native';

export const colors = {
  background: '#09090b',
  foreground: '#fafafa',
  primary: '#fafafa',
  secondary: '#27272a',
  secondaryForeground: '#d4d4d8',
  muted: '#27272a',
  mutedForeground: '#a1a1aa',
  info: '#3b82f6',
  brand: '#6366f1',
  success: '#22c55e',
  warning: '#eab308',
  error: '#ef4444',
  border: '#27272a',
  card: '#18181b',
} as const;

export const commonStyles = StyleSheet.create({
  flex1: { flex: 1 },
  bgBackground: { backgroundColor: colors.background },
  bgCard: { backgroundColor: colors.card },
  bgMuted: { backgroundColor: colors.muted },
  textForeground: { color: colors.foreground },
  textMutedForeground: { color: colors.mutedForeground },
  textBrand: { color: colors.brand },
  textSuccess: { color: colors.success },
  textWarning: { color: colors.warning },
  textError: { color: colors.error },
  borderBorder: { borderColor: colors.border },
  row: { flexDirection: 'row' },
  itemsCenter: { alignItems: 'center' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyCenter: { justifyContent: 'center' },
  gap1: { gap: 4 },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  gap4: { gap: 16 },
  p2: { padding: 8 },
  p3: { padding: 12 },
  p4: { padding: 16 },
  px2: { paddingHorizontal: 8 },
  px3: { paddingHorizontal: 12 },
  px4: { paddingHorizontal: 16 },
  py2: { paddingVertical: 8 },
  py3: { paddingVertical: 12 },
  py4: { paddingVertical: 16 },
  rounded: { borderRadius: 8 },
  roundedFull: { borderRadius: 9999 },
  border: { borderWidth: 1 },
  borderB: { borderBottomWidth: 1 },
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textBase: { fontSize: 16 },
  textLg: { fontSize: 18 },
  textXl: { fontSize: 20 },
  text2xl: { fontSize: 24 },
  fontMedium: { fontWeight: '500' },
  fontSemibold: { fontWeight: '600' },
  fontBold: { fontWeight: '700' },
  textCenter: { textAlign: 'center' },
});

export const statusColors = {
  pending: colors.warning,
  running: colors.brand,
  completed: colors.success,
  failed: colors.error,
  starting: colors.brand,
} as const;
